# Generated by Django 5.2 on 2025-04-14 07:33

import apps.services.utils
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Parameter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(blank=True, help_text='Поле слаг заполняется автоматически', max_length=255, unique=True, verbose_name='URL')),
                ('title', models.CharField(max_length=255, verbose_name='Параметр')),
            ],
            options={
                'verbose_name': 'Параметр',
                'verbose_name_plural': 'Параметры',
            },
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(blank=True, help_text='Поле слаг заполняется автоматически', max_length=255, unique=True, verbose_name='URL')),
                ('title', models.CharField(max_length=255, verbose_name='Название проекта')),
                ('description', models.TextField(verbose_name='Информация о проекте')),
                ('price', models.IntegerField(blank=True, null=True, verbose_name='Цена проекта')),
                ('plan_image', models.ImageField(upload_to=apps.services.utils.ProjectImagePath('plan_images'), verbose_name='Изображение схемы проекта')),
                ('created', models.DateTimeField(auto_now_add=True, help_text='Дата создания проекта', verbose_name='Дата создания')),
                ('updated', models.DateTimeField(auto_now=True, help_text='Дата обновления проекта', verbose_name='Дата обновления')),
                ('published', models.BooleanField(default=True, help_text='Убрать галочку если нужно снять с публикации', verbose_name='Публикация проекта')),
            ],
            options={
                'verbose_name': 'Neva проект',
                'verbose_name_plural': 'Neva проекты',
                'ordering': ['-created'],
            },
        ),
        migrations.CreateModel(
            name='ProjectImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to=apps.services.utils.ProjectImagePath('images'))),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='marga_design.project')),
            ],
            options={
                'verbose_name': 'Фотография проекта',
                'verbose_name_plural': 'Фотографии проекта',
            },
        ),
        migrations.CreateModel(
            name='ProjectParameter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('parameter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parameters_set', to='marga_design.parameter')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='project_parameters_set', to='marga_design.project')),
            ],
            options={
                'verbose_name': 'Параметр проекта',
                'verbose_name_plural': 'Параметры проектов',
            },
        ),
    ]
