# Generated by Django 5.2 on 2025-04-14 08:36

import apps.services.utils
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marga_design', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='plan_image',
            field=models.ImageField(blank=True, null=True, upload_to=apps.services.utils.ProjectImagePath('plan_images'), verbose_name='Изображение схемы проекта'),
        ),
    ]
