# Generated by Django 5.2 on 2025-04-14 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marga_design', '0002_alter_project_plan_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parameter',
            name='title',
            field=models.CharField(max_length=255, unique=True, verbose_name='Параметр'),
        ),
        migrations.AddConstraint(
            model_name='projectparameter',
            constraint=models.UniqueConstraint(fields=('parameter', 'project'), name='unique_project_parameter'),
        ),
    ]
