# Generated by Django 5.2 on 2025-04-17 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marga_design', '0004_project_location_project_top_rating_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='ФИО')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
                ('phone', models.CharField(max_length=20, verbose_name='Телефон')),
                ('message', models.TextField(verbose_name='Сообщение клиента')),
                ('note', models.TextField(blank=True, null=True, verbose_name='Примечание')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('answer', models.CharField(choices=[('NO', 'Не отвечено'), ('YES', 'Ответили'), ('PENDING', 'В ожидании ответа'), ('REFUSAL', 'Отказ'), ('AGREEMENT', 'Согласие')], default='NO', max_length=15, verbose_name='Ответ на заявку')),
            ],
        ),
    ]
