# Generated by Django 5.2 on 2025-04-18 10:52

import apps.services.utils
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marga_design', '0005_application'),
    ]

    operations = [
        migrations.CreateModel(
            name='BlogPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(blank=True, help_text='Поле слаг заполняется автоматически', max_length=255, unique=True, verbose_name='URL')),
                ('title', models.CharField(max_length=255, verbose_name='Название поста')),
                ('description', models.TextField(verbose_name='Описание поста')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('published', models.BooleanField(default=True, help_text='Убрать галочку если нужно снять с публикации', verbose_name='Статус')),
            ],
            options={
                'verbose_name': 'Пост',
                'verbose_name_plural': 'Посты',
                'ordering': ['-created'],
            },
        ),
        migrations.AlterModelOptions(
            name='application',
            options={'ordering': ['-created'], 'verbose_name': 'Заявка клиента', 'verbose_name_plural': 'Заявки клиентов'},
        ),
        migrations.AlterModelOptions(
            name='project',
            options={'ordering': ['-created'], 'verbose_name': 'Neva проект', 'verbose_name_plural': '  Neva проекты'},
        ),
        migrations.AlterField(
            model_name='application',
            name='answer',
            field=models.CharField(choices=[('NEW', 'Новая заявка'), ('WORK', 'В работе'), ('PENDING', 'В ожидании ответа'), ('REFUSAL', 'Отказ'), ('AGREEMENT', 'Согласие')], default='NO', max_length=15, verbose_name='Статус'),
        ),
        migrations.CreateModel(
            name='BlogPostImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to=apps.services.utils.ProjectImagePath('blog_images'), verbose_name='Изображения')),
                ('blog_post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='marga_design.blogpost')),
            ],
            options={
                'verbose_name': 'Изображение поста',
                'verbose_name_plural': 'Изображения поста',
            },
        ),
    ]
