# Generated by Django 5.2 on 2025-04-19 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marga_design', '0006_blogpost_alter_application_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='blogpost',
            options={'ordering': ['-created'], 'verbose_name': 'Блог', 'verbose_name_plural': 'Блог'},
        ),
        migrations.AlterField(
            model_name='blogpost',
            name='published',
            field=models.BooleanField(default=False, help_text='Убрать галочку если нужно снять с публикации', verbose_name='Статус'),
        ),
        migrations.AlterField(
            model_name='project',
            name='published',
            field=models.BooleanField(default=False, help_text='Убрать галочку если нужно снять с публикации', verbose_name='Статус'),
        ),
    ]
